### ISSUE TITLE
Não consigo criar a sessão

### ISSUE THREAD

**Issue by leandrocombr** [AlanMartines/mywhatsapp-api-node-wppconnect#3]
{ 'Status' => { 'state' => 'FAILURE', 'message' => "Authorization Token n\x{e3}o autorizada, verifique e tente novamente", 'result' => 'info', 'status' => 'notProvided' } }

Enviado

EEG02p8nrYmnqzcGDSegw3OlNrjUYhIE5k4x7KQHs
Teste

**Comment by AlanMartines** [comment]
Bom dia, estarei ajustando...

**Comment by AlanMartines** [comment]
> No campo AuthorizationToken passa o SECRET_KEY configurado no .env

👆
